### PR TITLE
version 1 for deployment on heroku

### PR DESCRIPTION
**Pull request by the-kaustubh**
Hey @sanketgarade,
This is the min working app, deploy-able on Heroku with DB hosted on Mongo Atlas.

Immediate next step would be to update our front-end static site and connect it to the back-end.

### CODE REVIEW

**Comment by sanketgarade** [comment]
Ok great 👍🏼. Thanks! 

Will you be submitting a PR for that separately on the front end repo?

**Comment by sanketgarade** [comment]
By the way, when submitting your next PR on the front end repo, please rename the _docs_ folder to _search_. All the **search site** stuff will go inside that folder, that's why. 

You can see that I've also created a _browse_ folder for the **browse site** separately.

**Comment by the-kaustubh** [comment]
Yes, I'll submit a separate PR for that as well on front end repo. 

> please rename the docs folder to search. All the search site stuff will go inside that folder, that's why.

Will do.

**Comment by sanketgarade** [comment]
@the-kaustubh 👋🏼 
any progress on this from your side?

**Pull request merged**
